
FROM alpine

#
# Install OpenSSH and set up display of out MOTD.
#
RUN apk add openssh bash && \
	echo "cat /etc/motd" >> /root/.bashrc

#COPY testing-ssh-config /root/.ssh/config
#COPY testing-motd /etc/motd

#
# This container isn't doing anything, other than being connected to
# via a "docker exec" command.
#
ENTRYPOINT /bin/sleep 999999


